name: SNAPSHOT - Build and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    name: Build and Publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.2.2
        with:
          distribution: zulu
          java-version: 17
      - name: Maven Publish
        env:
          GITHUB_ACTOR: '3dwardch3ng'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NEXUS_USERNAME: 'edward'
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          DEPLOYMENT_REPOSITORY_ID: ${{ secrets.DEPLOYMENT_REPOSITORY_ID }}
          SNAPSHOT_DEPLOYMENT_REPOSITORY_URL: ${{ secrets.SNAPSHOT_DEPLOYMENT_REPOSITORY_URL }}
          RELEASE_DEPLOYMENT_REPOSITORY_URL: ${{ secrets.RELEASE_DEPLOYMENT_REPOSITORY_URL }}
        run: |
          mvn -B deploy \
            -P homelab \
            --settings=${{ github.workspace }}/.mvn/settings.xml